# Generated by Django 6.0.5 on 2026-05-21 16:32

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0010_alter_host_id_alter_meeting_date_alter_meeting_id_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='meeting',
            name='date',
            field=models.DateField(default=datetime.datetime(2026, 5, 21, 22, 2, 14, 293832)),
        ),
        migrations.AlterField(
            model_name='meeting',
            name='time_in',
            field=models.TimeField(default=datetime.datetime(2026, 5, 21, 22, 2, 14, 293913)),
        ),
    ]
