# Generated by Django 6.0.5 on 2026-05-21 17:50

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0011_alter_meeting_date_alter_meeting_time_in'),
    ]

    operations = [
        migrations.AlterField(
            model_name='meeting',
            name='date',
            field=models.DateField(default=datetime.datetime(2026, 5, 21, 23, 20, 46, 450617)),
        ),
        migrations.AlterField(
            model_name='meeting',
            name='time_in',
            field=models.TimeField(default=datetime.datetime(2026, 5, 21, 23, 20, 46, 450644)),
        ),
    ]
